Makeup input
AlexanderLitvyakov/admin-panel pull request #3
Opened 2021-09-22 00:13 UTC by AlexanderLitvyakov

2021-09-25 16:30 UTC, Muslik requested changes
Есть замечания

2021-09-25 16:30 UTC, Muslik commented on blocks/input.html
> +      <input class="input__item input__item-lock" type="text" placeholder="Введите" value="16.12.2021">
lock и error - модификаторы. Значит через _

2021-09-25 16:30 UTC, Muslik commented on pages/index.html
> +        <div class="table-wrapper">
Просто table

2021-09-25 16:30 UTC, Muslik commented on pages/index.html
> +                    <div class="text-wrapper">Статус</div>
Названия классов не по БЭМ

2021-09-25 16:30 UTC, Muslik commented on pages/index.html
> +                <div class="filter__item-group_item1"></div>
У элемента не может быть только модификатора. Нужен основной класс блока/элемента.

2021-09-25 16:30 UTC, Muslik commented on pages/index.html
> +                    <div class="text-wrapper">Статус</div>
Верстать надо было вроде только первое задание. header таблицы делать было не нужно

2021-09-25 22:35 UTC, AlexanderLitvyakov commented
Исправил замечания, собственно должно быть красиво  \о/

2021-09-25 22:37 UTC, AlexanderLitvyakov commented on blocks/input.html
> +      <input class="input__item input__item-lock" type="text" placeholder="Введите" value="16.12.2021">
поменял

2021-09-25 22:37 UTC, AlexanderLitvyakov commented on pages/index.html
> +        <div class="table-wrapper">
убрал лишнее

2021-09-25 22:38 UTC, AlexanderLitvyakov commented on pages/index.html
> +                    <div class="text-wrapper">Статус</div>
сделал по БЭМ, да полез вперед, пришлось убрать всё, оставить нужное )))

2021-09-25 22:41 UTC, AlexanderLitvyakov commented on pages/index.html
> +                <div class="filter__item-group_item1"></div>
вот тут не совсем понятно, что не так, но исправил как понимаю.

2021-09-27 07:04 UTC, closed without merging

2021-09-27 07:04 UTC, AlexanderLitvyakov commented
Создан новый pr